import json
import os
import sqlite3
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, Tuple

import httpx


# путь к backend
def _webui_db_path() -> str:
    return str(Path(__file__).resolve().parents[2] / "data" / "webui.db")

def _db_connect() -> sqlite3.Connection:
    conn = sqlite3.connect(_webui_db_path(), timeout=10)
    conn.execute("PRAGMA busy_timeout=5000;")
    return conn

def _safe_json(obj: Any) -> str:
    try:
        return json.dumps(obj, ensure_ascii=False)
    except Exception:
        return '{"_error":"failed_to_json"}'

@dataclass
class SanitizeResult:
    raw_text: Optional[str]
    masked_text: Optional[str]
    has_pii: int              # 0/1
    policy_id: Optional[str]
    detector_version: Optional[str]
    updated_payload: dict     # payload with masked last user message (if any)
    is_user_input: bool       # True only for “real” user messages

def _extract_last_user_message(payload: dict) -> Tuple[Optional[int], Optional[str]]:
    """
    Returns: (index_in_messages, content)
    """
    msgs = payload.get("messages")
    if not isinstance(msgs, list):
        return None, None

    for i in range(len(msgs) - 1, -1, -1):
        m = msgs[i]
        if isinstance(m, dict) and m.get("role") == "user":
            return i, m.get("content")
    return None, None

def _content_to_text(content: Any) -> Optional[str]:
    if content is None:
        return None
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for p in content:
            if isinstance(p, dict):
                t = p.get("text")
                if p.get("type") in ("text", "input_text") and isinstance(t, str):
                    parts.append(t)
        return "\n".join(parts) if parts else None
    return str(content)

def _is_background_prompt(text: str) -> bool:
    # MVP heuristics to exclude follow-ups/tags prompts generated by OpenWebUI
    return text.startswith("### Task:") or "<chat_history>" in text

async def sanitize_payload_last_user_message(payload: dict) -> SanitizeResult:
    """
    - Extract last user message
    - Call sanitizer service (optional)
    - Replace that user message with masked_text in returned payload
    - Return raw/masked + has_pii (0/1)
    """
    updated = dict(payload)  # shallow copy
    idx, raw_content = _extract_last_user_message(updated)
    raw_text = _content_to_text(raw_content)

    # If no user message found
    if idx is None or not isinstance(raw_text, str) or not raw_text.strip():
        return SanitizeResult(
            raw_text=None,
            masked_text=None,
            has_pii=0,
            policy_id=None,
            detector_version=None,
            updated_payload=updated,
            is_user_input=False,
        )

    # Skip background prompts (follow-ups/tags/etc.)
    if _is_background_prompt(raw_text):
        return SanitizeResult(
            raw_text=None,
            masked_text=None,
            has_pii=0,
            policy_id=None,
            detector_version=None,
            updated_payload=updated,
            is_user_input=False,
        )

    policy_id = os.getenv("SANITIZER_POLICY", "default")
    sanitizer_url = os.getenv("SANITIZER_URL", "").strip()

    masked_text = raw_text
    has_pii = 0
    detector_version = None

    # If service not configured: keep as-is
    if sanitizer_url:
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                resp = await client.post(
                    sanitizer_url,
                    json={"text": raw_text, "policy_id": policy_id},
                )
                resp.raise_for_status()
                data = resp.json() if resp.content else {}

            masked_text = data.get("masked_text", raw_text)
            has_pii = int(data.get("has_pii", 0) or 0)
            policy_id = data.get("policy_id", policy_id)
            detector_version = data.get("detector_version")
        except Exception:
            # MVP: do not break chat if sanitizer fails
            masked_text = raw_text
            has_pii = 0

    # Update payload
    try:
        msgs = updated.get("messages")
        if isinstance(msgs, list) and idx < len(msgs) and isinstance(masked_text, str):
            if isinstance(msgs[idx].get("content"), list):
                msgs[idx]["content"] = [{"type": "text", "text": masked_text}]
            else:
                msgs[idx]["content"] = masked_text
    except Exception:
        # if anything goes wrong, return original payload unchanged
        updated = dict(payload)
        masked_text = raw_text
        has_pii = 0

    # Truncate extremely large inputs for DB safety (optional)
    if isinstance(raw_text, str) and len(raw_text) > 50_000:
        raw_text = raw_text[:50_000] + "...TRUNCATED"
    if isinstance(masked_text, str) and len(masked_text) > 50_000:
        masked_text = masked_text[:50_000] + "...TRUNCATED"
    print("AUDIT: extract idx=", idx, "raw_text_type=", type(raw_text), "raw_text_preview=", (raw_text[:80] if isinstance(raw_text, str) else raw_text))
    return SanitizeResult(
        raw_text=raw_text,
        masked_text=masked_text,
        has_pii=1 if has_pii else 0,
        policy_id=policy_id,
        detector_version=detector_version,
        updated_payload=updated,
        is_user_input=True,
    )

@dataclass
class LLMResponseMeta:
    user_id: Optional[str]
    session_id: Optional[str]
    conversation_id: Optional[str]
    message_id: Optional[str]

    provider: Optional[str]
    model: Optional[str]
    request_id: Optional[str]
    upstream_id: Optional[str]

    prompt_tokens: Optional[int]
    completion_tokens: Optional[int]
    total_tokens: Optional[int]
    latency_ms: Optional[int]
    cost_usd: Optional[float]

    meta_json: Optional[dict]  # without assistant text

def update_response_meta_usage(
    *,
    response_meta_id: str,
    prompt_tokens: Optional[int],
    completion_tokens: Optional[int],
    total_tokens: Optional[int],
    cost_usd: Optional[float],
    usage_details: Optional[dict] = None,
) -> None:
    conn = _db_connect()
    try:
        cur = conn.cursor()
        # дополним meta_json.usage_details (не обязательно)
        if usage_details is not None:
            cur.execute(
                "SELECT meta_json FROM response_meta WHERE id = ?",
                (response_meta_id,),
            )
            row = cur.fetchone()
            meta = {}
            if row and row[0]:
                try:
                    meta = json.loads(row[0])
                except Exception:
                    meta = {}
            meta["usage_details"] = usage_details
            meta_json = _safe_json(meta)
        else:
            meta_json = None

        if meta_json is not None:
            cur.execute(
                """
                UPDATE response_meta
                SET prompt_tokens = ?,
                    completion_tokens = ?,
                    total_tokens = ?,
                    cost_usd = ?,
                    meta_json = ?
                WHERE id = ?
                """,
                (
                    prompt_tokens,
                    completion_tokens,
                    total_tokens,
                    cost_usd,
                    meta_json,
                    response_meta_id,
                ),
            )
        else:
            cur.execute(
                """
                UPDATE response_meta
                SET prompt_tokens = ?,
                    completion_tokens = ?,
                    total_tokens = ?,
                    cost_usd = ?
                WHERE id = ?
                """,
                (
                    prompt_tokens,
                    completion_tokens,
                    total_tokens,
                    cost_usd,
                    response_meta_id,
                ),
            )

        conn.commit()
    finally:
        conn.close()

def insert_audit_rows(
    *,
    response_meta: LLMResponseMeta,
    raw_text: Optional[str],
    masked_text: Optional[str],
    has_pii: int,
    policy_id: Optional[str],
    detector_version: Optional[str],
) -> str:
    print("AUDIT: insert_audit_rows called, db_path =", _webui_db_path())
    response_meta_id = str(uuid.uuid4())
    request_text_id = str(uuid.uuid4())

    conn = _db_connect()
    try:
        cur = conn.cursor()

        # 1) всегда пишем response_meta
        cur.execute(
            """
            INSERT INTO response_meta (
              id, created_at,
              user_id, session_id, conversation_id, message_id,
              provider, model, request_id, upstream_id,
              prompt_tokens, completion_tokens, total_tokens,
              latency_ms, cost_usd,
              meta_json
            ) VALUES (
              ?, CURRENT_TIMESTAMP,
              ?, ?, ?, ?,
              ?, ?, ?, ?,
              ?, ?, ?,
              ?, ?,
              ?
            )
            """,
            (
                response_meta_id,
                response_meta.user_id,
                response_meta.session_id,
                response_meta.conversation_id,
                response_meta.message_id,
                response_meta.provider,
                response_meta.model,
                response_meta.request_id,
                response_meta.upstream_id,
                response_meta.prompt_tokens,
                response_meta.completion_tokens,
                response_meta.total_tokens,
                response_meta.latency_ms,
                response_meta.cost_usd,
                _safe_json(response_meta.meta_json or {}),
            ),
        )

        # 2) request_texts — только для реального user input
        print("AUDIT: raw_text is None?", raw_text is None)
        if raw_text is not None:
            print(
                "AUDIT: inserting request_texts, preview=",
                raw_text[:80] if isinstance(raw_text, str) else raw_text
            )
            cur.execute(
                """
                INSERT INTO request_texts (
                  id, created_at,
                  response_meta_id,
                  user_id, user_name, user_email, user_role,
                  session_id, conversation_id, message_id,
                  raw_text, masked_text,
                  has_pii,
                  policy_id, detector_version
                ) VALUES (
                  ?, CURRENT_TIMESTAMP,
                  ?,
                  ?, ?, ?, ?,
                  ?, ?, ?,
                  ?, ?,
                  ?,
                  ?, ?
                )
                """,
                (
                    request_text_id,
                    response_meta_id,
                    response_meta.user_id,
                    (response_meta.meta_json or {}).get("user_name"),
                    (response_meta.meta_json or {}).get("user_email"),
                    (response_meta.meta_json or {}).get("user_role"),
                    response_meta.session_id,
                    response_meta.conversation_id,
                    response_meta.message_id,
                    raw_text,
                    masked_text,
                    int(has_pii) if has_pii else 0,
                    policy_id,
                    detector_version,
                ),
            )

        print("AUDIT: committing...")
        conn.commit()
        return response_meta_id
    finally:
        conn.close()
